# Generated by Django 4.2.15 on 2024-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=100)),
                ('Poster', models.ImageField(upload_to='images')),
                ('Date', models.CharField(max_length=100)),
            ],
        ),
    ]
